# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-loki/main/jsonschema/configuration.schema.json
connection_settings:
  url:
    env: CONNECTION_URL
  headers:
    X-Scope-OrgID:
      env: LOKI_ORG_ID
  timeout: 30
  max_time_range: 30d
metadata:
  models: {}
  native_operations:
    queries: {}
runtime:
  flat: false
  unix_time_unit: ms
  format:
    timestamp: rfc3339
    value: float64
    nan: null
    inf: +Inf
    negative_inf: -Inf
